### ISSUE TITLE
Подготовить рабочее окружение:

### ISSUE THREAD

**Issue by CodingFeles** [Automiq/alpha.protort#119]
Qt Creator, Qt, Git клиент, Boost(1.55?)

**Comment by CodingFeles** [comment]
Qt, QtCreator: https://www1.qt.io/download-open-source/#section-9
Git: Любый удобный клиент. Например: клиент гитхаба или SourceTree атлассиана.

**Comment by CodingFeles** [comment]
С бустом и Qt не торопитесь, пока не уточню версию.

**Comment by CodingFeles** [comment]
Было решено устанавливать самые последние версии.

**Comment by IgorUsoltsev96** [comment]
10.10.2017 поставил последние `Qt`, `Qt Creator` и `boost`
СКВ буду использовать `Git GUI`
Суммарное время ≈ 40 минут.

**Comment by AlexMonster15** [comment]
11.10.2017 установил последние версии Qt, Qt Creator, Git, SourceTree, Boost
Суммарное время: 50 - 60 минут.

**Comment by Zubatov95** [comment]
11.10.2017 поставил Qt,Qt Creator, boost.
время работы примерно 60-80 минут

**Comment by Zubatov95** [comment]
11.10.2017 поставил Qt,Qt Creator, boost.
время работы примерно 60-80 минут

**Comment by reficul0** [comment]
12.10.2017 
Установил последние версии Qt , Qt Creator, Boost.
Затраченное время : 1 час

**Comment by ShlR0o** [comment]
Установил Qt  , Qt Creator , boost . 
Время : 80-100

**Comment by ShlR0o** [comment]
минут

**Comment by nnad** [comment]
12.10 Установила Qt , Qt Creator , boost .
Время 60 минут

**Comment by nnad** [comment]
До 13.10. 2017 все участники команды смогли установить рабочее окружение https://docs.google.com/spreadsheets/d/1HrPsN4dIt-9XGl3zCr_FnaawTU_Xr0xq8XFwHH-c0hQ/edit#gid=250050441

**Comment by nnad** [comment]
20.10.2017 4,5 часа установка windows sdk, boost, protobuf, попытка запустить проект
21.10.2017 1,2 часа устанока wdk, проект запустился под MinGW x32
