### ISSUE TITLE
Развернуть у себя ProtoRt

### ISSUE THREAD

**Issue by CodingFeles** [Automiq/alpha.protort#120]
Для начала развернём готовую часть решения.
Делать это скорее всего будем лично собравшись в офисе.

**Comment by nnad** [comment]
до 13.10.2017 никто из участников команды не сумел развернуть ProtoRt https://docs.google.com/spreadsheets/d/1HrPsN4dIt-9XGl3zCr_FnaawTU_Xr0xq8XFwHH-c0hQ/edit#gid=250050441

**Comment by Zubatov95** [comment]
отчет за 14.10.2017
пробовали развернуть проект.
скомпилировали protoBuf под msvc.
проблема с подключением к проекту boost и protobuf
Леша отработал с 18-30 до 20-20 (работал дома примерно час)
Женя c 17-30 до 20-20
Андрей с 17-00 до 20-00. (работал дома примерно час)
Александр работал дома(примерно 3 часа). Проблема с подключением к проекту.
Завтра опять собираем.
пробуксовка из-за недостатка знаний, будем устранять пробелы, изучать документацию.
--------------------------------------
15.10.2017 
развернули ProtoRt. 
Собрали под msvc-14.0x64(Андрей)
версии библиотек boost 1.65
protobuff 3

Собрали под msvc-14.1x64(Александр СОБРАЛ ПЕРВЫЙ)
версии библиотек boost 1.65
protobuff 3

проблемы:
указание верных путей к библиотекам. 
компиляция protobuf.

так же 15.10 вся команда посетила интенсивы.
каждый затратил 9 часов. 

теперь необходимо:
собрать под minGW.
собрать под msvc-14.0 x32

**Comment by nnad** [comment]
20.10.2017 4,5 часа установка windows sdk, boost, protobuf, попытка запустить проект
21.10.2017 1,2 часа устанока wdk, проект запустился под MinGW x32

**Comment by nnad** [comment]
24.10.2017 1,5 Пыталась развернуть под msvc с Windows SDK 8

**Comment by nnad** [comment]
25.10.2017 3,33 часа Была проведена встреча. В результате, удалось развернуть под MSCV 2017 x64.
