### ISSUE TITLE
Планирование расписания

### ISSUE THREAD

**Issue by CodingFeles** [Automiq/alpha.protort#121]

**Comment by CodingFeles** [comment]
Менеджером была избрана Анастасия. Задача полностью переходит к ней.

**Comment by CodingFeles** [comment]
@nnad отчитайся пожалуйста и можно закрывать задачу.

**Comment by nnad** [comment]
Было сделано расписание команды, доступно по ссылке https://docs.google.com/spreadsheets/d/1KiYYrP6YBtzGjjU1vegyYk7nB0o6lVvFtK-9jeve8Xk/edit#gid=0
