### ISSUE TITLE
отчет 14.10.2017

### ISSUE THREAD

**Issue by Zubatov95** [Automiq/alpha.protort#122]
пробовали развернуть проект. 
скомпилировали protoBuf под msvc. 
проблема с подключением к проекту boost и protobuf
Леша отработал с 18-30 до 20-20 (работал дома примерно час)
Женя c 17-30 до 20-20
Андрей с 17-00 до 20-00. (работал дома примерно час)
Александр работал дома(примерно 3 часа).  Проблема с подключением к проекту.  
Завтра опять собираем. 
пробуксовка из-за недостатка знаний, будем устранять пробелы, изучать документацию.

**Comment by CodingFeles** [comment]
@Zubatov95 Это надо перенести в #120 и отчитаться там.
