### ISSUE TITLE
Аналитика: необходимо собрать материалы для работы с проектом.

### ISSUE THREAD

**Issue by CodingFeles** [Automiq/alpha.protort#127]
Для работы с унаследованным проектом нужны материалы, например:
- Информация как собрать проект.
- Как пользоваться.

Нужно:
1) составить полный список;
2) назначить людей и выяснить у предыдущей команды все интересующие вопросы;
3) оформить материалы в вики.

**Comment by CodingFeles** [comment]
@Zubatov95 тут есть 3 взаимосвязанных пункта. Нужно назначить людей на эти задачи. Можно несколько. Не забывай, что скоро будут ещё задачи и нужно будет их тоже поручать людям.

**Comment by Zubatov95** [comment]
16.10.17 
встречались в офисе. 
присутствовали все члены команды. 
начало встречи 19-00
конец встречи 22-00

в ходе аналитики возникли следующие вопросы по проекту ProtoRt:
Логика сервера 
Структура проекта в целом
Работа терминала(функционал), конфигурация
Ограничения накладываемые на проект. 
Компоненты alpha.proto
Кто из себя представляют .proto файлы
Как происходит развертывание узлов с заданной конфигурацией 
Соединение client->server 
Проблемы взаимодействия linux/windows
Взаимодействие функции при помощи callback
Как устроена клиентская часть
Какие источники информации использовались в ходе работы
Какой набор протоколов используется при tcp соединение
Работа парсера 
Список вопросов будет дополняться в ходе работы над проектом

Необходимо:
  Получить информацию по текущим вопросам  у предыдущей команды.
  Оформить материалы в вики
Ответственные: 
  Игорь и Александр

**Comment by Zubatov95** [comment]
Составлен следующий список вопросов:
Работа терминала(конфигурация)
Как происходит соединение клиент-сервер
Актуальность информации wiki проекта
Развертка(как разворачиваются узлы на linux и windows)

**Comment by IgorUsoltsev96** [comment]
18.10.2017 
Проведена встреча с одним из бывших разработчиков Павлом Рабченюком.
Затраченное время (2 часа) будет зафиксировано каждым участником (Игорь, Александр) самостоятельно в эксель файле текущего спринта.

Необходимо:
оформить полученную от Павла информацию в wiki.
Ответственные:
Игорь и Александр

**Comment by Zubatov95** [comment]
18.10.2017 
Евгений аналитика проекта, описание некоторых компонент. 
Разобрался educe, history, timed_generator.
так же покопался в коде retranslator и terminator. 
Сделал описание хэдеров 
суммарное время работы 2 часа 15 минут.
Алексей занимался аналитикой, разбирался в исходном коде ProtoRt 
затраченное время 1.5 часа.  
Андрей занимался аналитикой, разбирался в исходном коде ProtoRt 
затраченное время 40 минут.

**Comment by AlexMonster15** [comment]
18.10.2017
Александр аналитика проекта, дополнил вики. Затраченное время 2.5 часа.
Игорь аналитика проекта, дополнил вики. Затрачено время 2.5 часа.

**Comment by Zubatov95** [comment]
Работа завершена. 
Ответственные: Игорь, Александр. 
Задача: собрать материалы для работы с проектом. 
Результат: Собрана необходимая информация. С информацией можно ознакомиться в wiki проекта.
Затрачено времени: 
Александр : 4,5 часа
Игорь :4,5 часа
Итог 9 часов.
