### ISSUE TITLE
Закрыть предыдущий спринт.

### ISSUE THREAD

**Issue by CodingFeles** [Automiq/alpha.protort#128]
Нужно разобраться с состоянием задач и передать проект.
#120 я перенёс во второй спринт и считаю, что здесь оно и должно быть.

По #119 надо разобраться: все ли это сделали, если кто-то не сделал, то помочь(надеюсь, что там минимум работу), отчитаться в задаче о результатах и закрыть.

#121 нужен отчёт и можно закрывать.

Как всё будет готово - закрываем первый спринт.

**Comment by nnad** [comment]
Итоги до 13.10.2017:

- Никто из участников команды не сумел развернуть ProtoRt
- Все участники команды установили рабочее окружение
- Было составлено расписание
