### ISSUE TITLE
Аналитика: анализ структуры проектов parser и components.

### ISSUE THREAD

**Issue by IgorUsoltsev96** [Automiq/alpha.protort#130]

**Comment by Zubatov95** [comment]
18.10.2017 
Евгений аналитика проекта, описание некоторых компонент. 
Разобрался educe, history, timed_generator.
так же покопался в коде retranslator и terminator. 
Сделал описание хэдеров 
суммарное время работы 2 часа 15 минут.
Алексей занимался аналитикой, разбирался в исходном коде ProtoRt 
затраченное время 1.5 часа.  
Андрей занимался аналитикой, разбирался в исходном коде ProtoRt 
затраченное время 40 минут.
подготовка результатов будет оформлена в скором времени.

**Comment by reficul0** [comment]
Была проведена аналитика структуры проектов parser и components, по которой производилась 
 документация.
Результаты залиты в репозиторий: https://github.com/reficul0/alpha.protort.documentation
Затраченное время 2 часа 30 минут

**Comment by Zubatov95** [comment]
Задача выполнена. 
Евгений потратил 4 часа :45 минут.
Алексей 1 час 30 минут
Андрей 40 минут.
Суммарно затрачено времени:
6 часов 55 минут.  
С результатами можно ознакомиться оп ссылке 
https://github.com/reficul0/alpha.protort.documentation
