### ISSUE TITLE
Аналитика: разбор задач

### ISSUE THREAD

**Issue by reficul0** [Automiq/alpha.protort#138]

**Comment by ShlR0o** [comment]
24 число занимался аналитикой в офисе с 13:00 до 18:00

**Comment by ShlR0o** [comment]
Аналитика по проекту ProtoRt завершена. Затрачено времени 10 часов .
[Документ.docx](https://github.com/Automiq/alpha.protort/files/1417570/default.docx)

**Comment by ShlR0o** [comment]
в файле перечислены функциональные требования и сценарии работы с системой
