### ISSUE TITLE
Произвести тест производительности первой версии сетевого стека

### ISSUE THREAD

**Issue by dstftw** [Automiq/alpha.protort#38]
На примере приложения сетевого узла и простейших конфигураций:
- node(g) -> node(t)
- node(g) -> node(r) -> node(t)

(прим. g = generator, r = retranslator, t = terminator)
проверить прохождение пакетов и измерить производительность их передачи.

Методика тестирования:
1. Сгенерировать N пакетов на узле генераторе и измерить время за которое они будут переданы удаленной стороне.
2. На узле терминаторе измерить время, за которое все пакеты будут обработаны.

Проверить на петле и не реальном сетевом линке между двумя реальными сетевыми машинами.

Рассчитать основные показатели KPI, такие как пропуская способность, latency, загрузка процессора.

**Comment by dstftw** [comment]
Intel Core i7-2600, loopback, single core, 200 KiB packet x 10k times.
Windows 10, 3.83 seconds = ~3.5-4 GBit/s
Ubuntu Xenial Xerus 16.04 (VMware) = ~12 GBit/s (что-то здесь не так, не ясно откуда такое преимущество по сравнению с Windows)

**Comment by ZHURAVLEVSS** [comment]
##### Результат теста на localhost Processor Intel Celeron CPU B830 @ 1.80 GHz

```
alpha.protort.link.nodebenchmark.exe --destination 127.0.0.1:10000 -n generator --npackets 10000 --packet-size 200000
ctr
start
npacket:10000
size of packet: 200000
on_connect system:0
Run time: 6.71489
Speed: 0.432049
Speed (GBit/s): 2.21912
```

**Comment by dstftw** [comment]
Результаты обобщены в [Wiki](https://github.com/Automiq/alpha.protort/wiki/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BF%D1%80%D0%BE%D0%BF%D1%83%D1%81%D0%BA%D0%BD%D0%BE%D0%B9-%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%B8-%D0%B1%D1%8B%D1%81%D1%82%D1%80%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F).
