### ISSUE TITLE
Реализовать базовый вариант библиотеки сетевого взаймодействия (alpha.protort.link)

### ISSUE THREAD

**Issue by kimolegan** [Automiq/alpha.protort#4]
**Рабочее название:** alpha.protort.link

**Требования:**
- должна быть выполнена в виде статической библиотеки
- возможность устанавливать и поддерживать соединение по протоколу TCP/IP с определенным узлом host:port
- возможность доставки пакетов
- возможность прослушивания порта на предмет входящий подключений
- возможность приема пакетов

**Comment by kimolegan** [comment]
Библиотека должна быть статичной

**Comment by dstftw** [comment]
Декомпозировано в #16 и #17.
