### ISSUE TITLE
Проработка требований для приложения терминала

### ISSUE THREAD

**Issue by dwlttpr** [Automiq/alpha.protort#43]
- Спланировать основной функционал
- Проработать use cases
- Подготовить план работ по разработке приложения терминала

**Comment by dstftw** [comment]
Дополнение: требования нужно приоритизировать.

**Comment by dstftw** [comment]
> ЗАГРУЗИТЬ СХЕМУ распределённого приложения в текстовом формате

Что за схема такая? Есть только схема развертывания.

> РАЗВЕРНУТЬ СХЕМУ

Что значит развернуть схему?

> СТАРТ по схеме
> ПАУЗА по схеме
> СТОП по схеме

Не ясно.

План работ нужно выразить в виде [тикетов](https://github.com/Automiq/alpha.protort/issues).
