### ISSUE TITLE
Реализовать слой взаимодейстия по бинарному протоколу 

### ISSUE THREAD

**Issue by dstftw** [Automiq/alpha.protort#73]
В ходе проработки бинарного протокола, стало ясно, что необходим еще один слой абстракции между библиотекой `link` и библиотекой развертывания - назовем его `protolink`.

Предназначение этого слоя:
1. Устранить необходимость работы с сырыми данными уровня `link` (буфер байтов) и переложить ее на работу в терминах `Payload` бинарного протокола `alpha.protort.protocol`.
2. Предоставить удобный интерфейс для отправки всех возможных типов пакетов протокола `alpha.protort.protocol` (сообщение, запрос, ответ).
3. Предоставить удобный интерфейс для получения ответа на посланный запрос.

Предполагается реализация в вышеописанном объеме.

**Comment by kimolegan** [comment]
Декомпозировано в #81, #82
